### ISSUE TITLE
estimate.invoiceEstimate should return undefined instead of empty {} if none are found

### ISSUE THREAD

**Issue by julianCast** [chargebee/chargebee-node#43] opened 2024-06-20 11:03 UTC
### Description of the Bug

I believe we should get  null instead of { } in the cases of  no invoices estimate. That object can cause trouble for notNullable fields. That would make the field `invoice_estimate.sub_total` be undefined, when it's not an optional parameter in your documentation.

### Steps to reproduce

Check the output for a subscription which has no next invoice, so no `invoice_estimate`      
```ts
const response = await chargebee.estimate.renewal_estimate(subscriptionId).request();
console.log(response.estimate.invoice_estimate) // {}, instead of undefined
```

### Expected Behavior

```ts
Estimate {
  created_at: 1718879521,
  object: 'estimate',
  subscription_estimate: SubscriptionEstimate {
    id: '12C9UGDmLHI2CC',
    status: 'non_renewing',
    object: 'subscription_estimate',
    currency_code: 'EUR',
    shipping_address: ShippingAddress {
      first_name: 'John',
      last_name: 'Doe',
     ...
      validation_status: 'not_validated',
      object: 'shipping_address'
    }
  },
  invoice_estimate: undefined <---- Shouldn't this be the response?
  next_invoice_estimate: null
}
```

### Code Snippets (if applicable)

```node
Estimate {
  created_at: 1718879521,
  object: 'estimate',
  subscription_estimate: SubscriptionEstimate {
    id: '12C9UGDmLHI2CC',
    status: 'non_renewing',
    object: 'subscription_estimate',
    currency_code: 'EUR',
    shipping_address: ShippingAddress {
      first_name: 'John',
      last_name: 'Doe',
      validation_status: 'not_validated',
      object: 'shipping_address'
    }
  },
  invoice_estimate: InvoiceEstimate {},<---- CB response instead of undefined ?
  next_invoice_estimate: InvoiceEstimate {}
}
```

### Operating System

macOS

### Language version

Node 18.17.0

### Library version

2.32.1

### Additional context

This incurs in error if we are returning estimate via graphql where the field invoice_estimate.sub_total was set as `NonNegativeInt!`.

**Comment by cb-sriramthiagarajan** [comment] 2024-06-21 11:47
Hi @julianCast, I just checked this and this looks to be returning `undefined` when there's no `invoice_estimate` as expected. 

Could you confirm if you see the empty object when you hit the API via `curl` or any other REST client?

**Comment by julianCast** [comment] 2024-06-21 12:32
> Hi @julianCast, I just checked this and this looks to be returning `undefined` when there's no `invoice_estimate` as expected.
> 
> Could you confirm if you see the empty object when you hit the API via `curl` or any other REST client?

Here's the thing. 
To reproduce it, I create a subscription, with a yearly plan, modify the price to 0 and after that I cancel it (end of term)

❌ Using this library node js (Got the {})
<img width="1040" alt="image" src="https://github.com/chargebee/chargebee-node/assets/559677/453fbb6d-c227-4912-80ae-70f494e4b267">

✅  Using regular HHTP in Postman (Doesn't return the attribute since is undefined)
<img width="739" alt="image" src="https://github.com/chargebee/chargebee-node/assets/559677/753b2730-1b9e-4ab5-b45b-63764f5beb7c">

**Comment by cb-sriramthiagarajan** [comment] 2024-06-21 13:48
Thanks for sharing this @julianCast. I don't seem to be able to reproduce this with the same flow & code snippet 😕 

Just to be sure, is the `chargebee` object in the code sample you shared coming directly from our SDK or do you have any wrapper on top? Also, is there any layer that could possibly modify the response?

**Comment by julianCast** [comment] 2024-07-01 12:06
Hi! Thanks for following this:
Yes, I'm actually just using the SDK.
```tsx
import { ChargeBee } from 'chargebee-typescript';

const chargebee = new ChargeBee();
```

**Comment by cb-sriramthiagarajan** [comment] 2024-07-23 04:03
Hi @julianCast, I'm sorry I missed sharing an update earlier. We looked into this and realized that the issue is indeed present in [chargebee-typescript](https://github.com/chargebee/chargebee-typescript) but not chargebee-node (which is this repo). We've identified the cause for this and working on a fix which would be released in about a week. We'll update here once the fix is released. Thanks for your patience.

**Comment by julianCast** [comment] 2024-07-23 20:15
> Hi @julianCast,..We've identified the cause for this and working on a fix which would be released in about a week. We'll update here once the fix is released. Thanks for your patience.

That's great news! Thank you for working on it!

**Comment by tsriram** [comment] 2024-08-01 11:40
Hi @julianCast, this issue is fixed in [v2.37.0](https://www.npmjs.com/package/chargebee-typescript/v/2.37.0). Can you please give it a try and see if it works for you?

**Comment by cb-sriramthiagarajan** [comment] 2024-08-01 11:42
Hi @julianCast, this issue is fixed in [v2.37.0](https://www.npmjs.com/package/chargebee-typescript/v/2.37.0). Can you please give it a try and see if it works for you?

**Comment by julianCast** [comment] 2024-08-08 11:09
Thank you, I will and I'll let you know

**Comment by cb-sriramthiagarajan** [comment] 2024-08-30 10:42
Hi @julianCast, I'm closing this issue for now. Please feel free to reopen if you're still facing this. Thanks!

**Closed by cb-sriramthiagarajan** 2024-08-30 10:42 UTC

**Comment by julianCast** [comment] 2024-08-30 11:15
> Hi @julianCast, I'm closing this issue for now. Please feel free to reopen if you're still facing this. Thanks!

Thank you, I haven't tested yet I'm sorry, but I'll reopen if it occurs.

**Comment by cb-sriramthiagarajan** [comment] 2024-08-30 13:18
No worries @julianCast. 

Also, it'd be great if you could give v3 beta a go when you get a chance and share feedback. More details on #46.
